<?php $title='Esenzioni'; ; 
$this->headTitle($title); ?>
<section >
    <div class='riassunto_titlebox' style="background-color: #f14545;">
        <img src='<?= $this->basePath(); ?>/img/icone72dpi/icone72dpi-24.png'/>ALLERGIE
    </div>
    <div style="padding: 0.5em">
        <div class="col-xs-5">Pennicillina</div>
        <div class="col-xs-5">Grave</div>
        
    </div>
    <div class="col-xs-offset-9" style="padding-top: 10em;">
        <a href='profile?action=allergie'>
            <input type="button" value="VEDI TUTTE" class="btn_standard"/>
        </a>
    </div>
    
</section>
