<?php $title='Esenzioni'; ; 
$this->headTitle($title); ?>
<section>
    <div class="section_title" style="color: <?php echo $this->color ?>">
        <h2>ALLERGIE</h2>
    </div>
    <div style="clear: both" class="text-right">
        <input type="button" class="btn_standard" value="STAMPA TUTTE" style="background-color: <?php echo $this->color; ?>; color: #FFFFFF"/>
    </div>
    <div>
        <table class="table_allergie">
            <tr class="tr_th">
                <th>A cosa</th>
                <th>Reazione</th>
                <th>Gravità</th>
                <th>Note</th>
            </tr>
            <tr>
                <td>Pennicillina</td>
                <td>Pustole nel punto di contatto, gonfiore lingua e mancanza d'ossigeno</td>
                <td>Grave</td>
                <td>Spuntata all'età di 10 anni, trattata con farmaci
                </td>
            </tr>
        </table>
    </div>
</section>
