<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <br>
    <div class="row">
        <?php $redirect = array(
            'riassunto',
            'comunicazioni',
            'anagrafica',
            'calendario',
            'esenzioni',
            'allergie',
            'esamiDiLaboratorio',
            'procedureDiagnostiche',
            'terapiaContinuativa',
            'ricetteDematerializzate',
            'certificatiInps',
            'diarioDiagnostico',
            'famiglia',
            'procedureTerapeutiche',
            'problemiChiave',
            'presidi',
            'pianiTerapeutici',
            'scadenze'); ?>
        <?php for ($i = 1; $i<10; $i++){ ?>
        <a href="profile?action=<?php echo $redirect[$i-1]; ?>" class="col-xs-0">
                <?php if ($this->img_index <> $i){ ?>
            <img src="<?= $this->basePath(); ?>/img/icone72dpi/icone72dpi-0<?php echo $i?>.png" title="<?php echo $redirect[$i-1]; ?>" />
                <?php } else { ?>
                    <img src="<?= $this->basePath(); ?>/img/icone72dpi/icone72dpi-<?php echo $i+18?>.png"  title="<?php echo $redirect[$i-1]; ?>"/>
                <?php } ?>
            </a>
        <?php } ?>
        <?php for ($i = 10; $i<=18; $i++){ ?>
            <a href="profile?action=<?php echo $redirect[$i-1]; ?>" class="col-xs-0">
                <?php if ($this->img_index <> $i){ ?>
                    <img src="<?= $this->basePath(); ?>/img/icone72dpi/icone72dpi-<?php echo $i?>.png"  title="<?php echo $redirect[$i-1]; ?>"/>
                <?php } else { ?>
                    <img src="<?= $this->basePath(); ?>/img/icone72dpi/icone72dpi-<?php echo $i+18?>.png"  title="<?php echo $redirect[$i-1]; ?>"/>
                <?php } ?>
            </a>
        <?php } ?>
        
    </div>
    <br/><b/>
</html>
