<?php $title='Esenzioni'; ; 
$this->headTitle($title); ?>
<section >
    <div class='riassunto_titlebox' style="background-color: #31b16e;">
        <img src='<?= $this->basePath(); ?>/img/icone72dpi/icone72dpi-25.png'/>ESAMI DI LABORATORIO
    </div>
    <div style="padding: 0.5em">
        <div class="col-xs-5">Ferro<br/>4 Dicembre 2014</div>
        <div class="col-xs-5" style="text-align: center;">2<br/>(3,5-5,5)mml/I</div>
        <div class="col-xs-1"><img src='<?= $this->basePath(); ?>/img/icone72dpi/icone72dpi-56.png'/></div>
    </div>
    <div class="col-xs-offset-9" style="padding-top: 10em;">
        <a href='profile?action=esamiDiLaboratorio'>
            <input type="button" value="VEDI TUTTI" class="btn_standard"/>
        </a>
    </div>
    
</section>
