<?php $title='Esenzioni'; ; 
$this->headTitle($title); ?>
<section >
    <div class='riassunto_titlebox' style="background-color: #afeed8;">
        <img src='<?= $this->basePath(); ?>/img/icone72dpi/icone72dpi-23.png'/>ESENZIONI
    </div>
    <div style="padding: 0.5em">
        <div class="col-xs-1"><img src="<?= $this->basePath(); ?>/img/icone72dpi/icone72dpi-70.png"/></div>
        <div class="col-xs-11">
            <b>Esenzione E05</b><br/>
            Scaduta il 20 febbraio
        </div>
    </div>
    <div class="col-xs-offset-9" style="padding-top: 10em;">
        <a href='profile?action=esenzioni'>
            <input type="button" value="VEDI TUTTE" class="btn_standard"/>
        </a>
    </div>
</section>
