<?php $title='Riassunto'; ; 
$this->headTitle($title); ?>
<section>
    <div class="section_title" style="color: <?php echo $this->color ?>">
        <h2>RIASSUNTO</h2>
    </div>
    <div class='col-xs-6'><?php include('allergie_mini.phtml'); ?></div>
    <div class='col-xs-6'><?php include('esenzioni_mini.phtml'); ?></div>
    <div class='col-xs-6'><?php include('esamiDiLaboratorio_mini.phtml'); ?></div>
    <div class='col-xs-6'><?php include('procedureDiagnostiche_mini.phtml'); ?></div>
    <div style="clear: both;"></div>
</section>
